# Home Lab Portal: a read-only dashboard for the services on this machine.
#
# The module is deliberately dependency free. The backend is a single Python
# standard-library script and the frontend is plain HTML/CSS/JS, so the whole
# site is built by Nix without a JavaScript toolchain or a separate build step.
#
# Everything the unit reads is named as a store path (the server script, the
# static assets, the documentation, and the inventory). A content-only change
# therefore changes the unit and Home Manager's sd-switch restarts it, which is
# the same pattern the other host services use.
#
# The service is read-only by construction: it exposes inventory and live state
# and offers no endpoint that can change a systemd unit or a service.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.hostServices.homelabPortal;

  portalDir = ../../config/homelab/portal;

  # The server script is kept out of the static directory so that no asset path
  # can ever reach it; the HTTP handler also serves a fixed asset whitelist.
  serverScript = pkgs.writeText "homelab-portal-server.py" (
    builtins.readFile (portalDir + "/server.py")
  );

  staticDir = pkgs.runCommand "homelab-portal-static" { } ''
    mkdir -p $out
    cp ${portalDir + "/index.html"} $out/index.html
    cp ${portalDir + "/styles.css"} $out/styles.css
    cp ${portalDir + "/app.js"} $out/app.js
    cp ${portalDir + "/markdown.js"} $out/markdown.js
  '';

  # Only Markdown is published to the reader endpoint. The larger dashboard
  # templates in docs/ stay out of the store and out of the HTTP surface.
  docsDir = pkgs.runCommand "homelab-portal-docs" { } ''
    mkdir -p $out
    cp ${../../docs}/*.md $out/
  '';

  inventoryFile = ../../config/homelab/inventory.json;

  environment = [
    "INVENTORY_PATH=${inventoryFile}"
    "STATIC_DIR=${staticDir}"
    "DOCS_DIR=${docsDir}"
    "BIND_HOST=${cfg.bindHost}"
    "BIND_PORT=${toString cfg.port}"
    "SYSTEMCTL_BIN=${cfg.systemctlBin}"
    "TAILSCALE_BIN=${cfg.tailscaleBin}"
    "STATUS_CACHE_SECONDS=${toString cfg.statusCacheSeconds}"
    "OPENOBSERVE_WINDOW_SECONDS=${toString cfg.openobserveWindowSeconds}"
  ]
  ++ lib.optional (cfg.openobserveBase != null) "OPENOBSERVE_BASE=${cfg.openobserveBase}"
  ++ lib.optional (cfg.openobserveEnvFile != null) "OPENOBSERVE_ENV_FILE=${cfg.openobserveEnvFile}";
in
{
  options.hostServices.homelabPortal = {
    enable = lib.mkEnableOption "read-only Home Lab Portal for service inventory and live status";

    bindHost = lib.mkOption {
      type = lib.types.str;
      default = "100.100.10.1";
      description = ''
        Address the HTTP server binds to. The default is this host's Tailscale
        address, so the portal is reachable from the tailnet and not from the
        LAN or the public internet.
      '';
    };

    port = lib.mkOption {
      type = lib.types.port;
      default = 8090;
      description = "TCP port for the portal HTTP server.";
    };

    statusCacheSeconds = lib.mkOption {
      type = lib.types.number;
      default = 5;
      description = ''
        How long one computed status snapshot is reused. Probes and systemctl
        calls are the expensive part; the page refreshes more often than this.
      '';
    };

    openobserveBase = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "http://100.100.10.1:5080";
      description = ''
        OpenObserve base URL used for the cross-host view. Set to null to
        disable the fleet panel entirely.
      '';
    };

    openobserveEnvFile = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "/data/openobserve/openobserve.env";
      description = ''
        Local OpenObserve environment file, read at runtime for the credentials
        used by the cross-host queries. The file is generated by the
        OpenObserve provisioning step; it is never part of the repository and
        never leaves this host. The ingestion token used by the collector is
        write-only and cannot be reused for queries.
      '';
    };

    openobserveWindowSeconds = lib.mkOption {
      type = lib.types.ints.positive;
      default = 900;
      description = "Lookback window for the cross-host metric queries.";
    };

    systemctlBin = lib.mkOption {
      type = lib.types.str;
      default = "/usr/bin/systemctl";
      description = ''
        systemctl used to read user unit state. This host runs standalone Home
        Manager on Fedora, so the binary comes from the distribution.
      '';
    };

    tailscaleBin = lib.mkOption {
      type = lib.types.str;
      default = "/usr/bin/tailscale";
      description = "Tailscale CLI used to read tailnet identity and serve state.";
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.user.services.homelab-portal = {
      Unit = {
        Description = "Home Lab Portal (read-only service inventory and live status)";
        Documentation = [ "file://${docsDir}/homelab-portal.md" ];
        After = [ "network-online.target" ];
        Wants = [ "network-online.target" ];
      };
      Service = {
        Type = "simple";
        ExecStart = "${pkgs.python3}/bin/python3 ${serverScript}";
        Environment = environment;
        Restart = "always";
        RestartSec = "5s";
        # The HTTP handler and the probes run in-process; nothing here needs
        # elevated privileges or a writable system path.
        NoNewPrivileges = true;
      };
      Install.WantedBy = [ "default.target" ];
    };
  };
}
